Sage-Bionetworks/sandbox-infra

- templates/accounts.yaml
> add account

- templates/accounts.yaml
> Add thomas's PHCCP user and code deploy group

- templates/accounts.yaml
It is unclear to me if I have to do anything special for scicomp access
> Updated accounts.yaml with my user information

- templates/accounts.yaml
I would like to request an AWS account. Thanks!
> Requesting account for Jineta Banerjee

- templates/accounts.yaml
> Create account for Robert Minneker

- templates/accounts.yaml
Attempt to keep sandbox and scicomp accounts consistent.  This is the
same as scicomp PR: https://github.com/Sage-Bionetworks/scicomp-infra/pull/199
> Add policy to view usage and billing reports, and assign policy

- templates/accounts.yaml
For the purposes of testing the Tibanna workflow engine.
> AWS IAM Admin role request

- templates/accounts.yaml
I believe the necessary sandbox resources have been re-owned, so this should succeed. https://sagebionetworks.jira.com/browse/IT-660
> Removing KimYen's IAM user

- templates/accounts.yaml
> Remove aabaker iam user

- config/prod/sage-tgw-sandcastlevpc.yaml
This depends on PR https://github.com/Sage-Bionetworks/aws-infra/pull/182
> setup a spoke attachment to the transit gateway hub

- config/prod/cfn-s3objects-macro.yaml
Deploy macro in PR https://github.com/Sage-Bionetworks/aws-infra/pull/211
> install the cloudformation s3object macro

- templates/accounts.yaml
I'm new & need to create AWS account, thanks!
> add_AWS_for_lauraheath

- templates/accounts.yaml
This is a dev user for sandbox
> adds danwebster as IAM user

- templates/accounts.yaml
DO NOT MERGE, yet, pending reassignment of resources.
> Remove Sara Gosline IAM user

- templates/accounts.yaml
> Remove Thomas Corey IAM user

- config/prod/cfn-ssm-param-macro.yaml
- config/prod/sc-enduser-iam.yaml
- config/prod/sc-portfolio-ec2.yaml
Setup the same EC2 portfolio as scipoolprod for testing
> [SC-111] setup portfolio in service catalog

- config/prod/cfn-sc-actions-provider.yaml
install the SC actions provider[1] cloudformation custom resource
into scipoolprod account
[1] https://github.com/Sage-Bionetworks/aws-infra/tree/master/lambdas/cfn-sc-actions-provider
> [SC-26] Install SC actions custom resource

- config/prod/AccountAlertTopics.yaml
- config/prod/bootstrap.yaml
- config/prod/cfn-explode-macro.yaml
- config/prod/cfn-s3objects-macro.yaml
- config/prod/essentials.yaml
- config/prod/park-my-cloud.yaml
- config/prod/peer-vpn-sandcastlevpc.yaml
- config/prod/rotate-credentials.yaml
- config/prod/s3-gateway-vpc-endpoint.yaml
- config/prod/sage-tgw-sandcastlevpc.yaml
- config/prod/sandcastlevpc.yaml
- config/prod/service-linked-roles.yaml
New version of sceptre has a before_launch hook that takes
care of before_create and before_update so all we need now is
one hook instead of two.
> refactor sceptre command

- templates/accounts.yaml
> Create IAM role for Kara

- templates/accounts.yaml
> Create IAM role for Nicole Kauer

- templates/accounts.yaml
Pending removal of resources in the account.
> Remove Kenneth Daily IAM user

- templates/accounts.yaml
Do not merge yet; pending migration of resources.
Passes precommit.
> Remove Eva Monsen IAM

- config/prod/accounts.yaml
- config/prod/iam-policies.yaml
- config/prod/jumpcloud-idp.yaml
- templates/iam-policies.yaml
- templates/jumpcloud-idp.yaml
Give sandbox developers some additional access
> Give developers additional access

- templates/accounts.yaml
Found no sandbox resources for this IAM entity.
> Remove user entity for offboarding
